DEFINE
	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			ROLLUPADDISSUBTOTAL('DimBusinessUnit'[BusinessUnitName], "IsGrandTotalRowTotal"),
			"SumTotalSaleAmount", CALCULATE(SUM('FactSales'[TotalSaleAmount])),
			"SumInvoiceAmount", CALCULATE(SUM('FactReceivables'[InvoiceAmount]))
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(502, __DS0Core, [IsGrandTotalRowTotal], 0, 'DimBusinessUnit'[BusinessUnitName], 1)

EVALUATE
	__DS0PrimaryWindowed

ORDER BY
	[IsGrandTotalRowTotal] DESC, 'DimBusinessUnit'[BusinessUnitName]