table Top/Bottom
	isHidden
	lineageTag: 5ef08e6d-ce79-478d-a632-e02c431ac76e

	column Column1
		dataType: string
		isHidden
		lineageTag: dabc9ce5-6d0d-496c-b47b-62ae775a67b8
		summarizeBy: none
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		isHidden
		lineageTag: 2534d312-8b6c-4d8d-ad52-aa82d303b5d9
		summarizeBy: none
		sourceColumn: Column2

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Top/Bottom = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCskvUNJRMlSK1YlWcsovKcnPBXKNlGJjAQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t])
				in
				    Source

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

